config/routes.rb
Rails.application.routes.draw do

  

get "index" => "lectures#index" , as: :index
  get 'lectures/new'
  get "new" => "lectures#new", as: :new
  get 'lectures/create'
  get 'lectures/destroy'
  get 'lectures/:id' => "lectures#show" , as: :lecture
  get 'image/:id' => "image#show"
  resources :lectures, only: [:index, :new, :create, :destroy,:show]

  root 'page#home' # tmam
  get "library" => "page#library", as: :library # msh mohem
  get "upload" => "page#upload", as: :upload   # msh mohem

  devise_for :users    #tmam

end

app/models/comment.rb
class Comment < ActiveRecord::Base
module Commentator
  
    belongs_to :commentable, polymorphic: true
    belongs_to :owner, class_name: Commentator.owner_class
    belongs_to :slide, class_name: 'Comment'

    has_many :replies, foreign_key: :slideNumber,
      class_name: 'Comment', dependent: :destroy

    default_scope order(:created_at)

    scope :base, where(slideNumber: nil)
  end

end

app/models/document.rb
class Document < ActiveRecord::Base
has_many :lectures, dependent: :delete_all
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :lecture
end

app/models/lecture.rb
class Lecture < ActiveRecord::Base
has_many :image, dependent: :delete_all
belongs_to :document
mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
validates :name, presence: true # Make sure the owner's name is present.

end

app/models/slide.rb
class Slide < ActiveRecord::Base
 belongs_to :document
acts_as_commentable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    before_action :authenticate_user!
end

app/controllers/comment_controller.rb
class CommentController < ApplicationController
require_dependency "commentator/application_controller"

module Commentator
  class CommentsController < ApplicationController
    before_filter :comment
    before_filter :commentable
    before_filter Commentator.authorize_method

    def reply
      new_comment = Comment.new(parent_id: params[:id],
                                commentable: commentable)
      render partial: 'commentator/comments/form',
             locals: {
               comment: new_comment,
               commentable: commentable,
             },
             layout: false
    end

    def create
      comment.commentable = commentable
      comment.owner = send(Commentator.current_commenter_method)
      if comment.save
        render partial: 'commentator/comments/comment',
          locals: { comment: comment }, layout: false, status: :created
      else
        render partial: 'comments/form',
          layout: false, status: :unprocessable_entity
      end
    end

    def update
      if comment.update_attributes(params[:comment])
        render partial: 'commentator/comments/comment',
          locals: { comment: comment }, layout: false, status: :created
      else
        render partial: 'comments/form',
          layout: false, status: :unprocessable_entity
      end
    end

    def destroy
      comment.destroy
      render json: comment, status: :ok
    end

  private
    def comment_params
      params.require(:comment).permit(:body, :parent_id)
    end

    def comment
      @comment ||=
        (params[:id] ?
          Comment.find(params[:id]) :
          (params[:comment] ?
            Comment.new(comment_params) :
            Comment.new))
    end

    def commentable
      @commentable ||= comment.commentable
      @commentable ||=
        params[:comment][:commentable_type].constantize.
          find(params[:comment][:commentable_id])
    end

    def always_allow_comment
      true
    end
  end
end
end

app/controllers/document_controller.rb
class DocumentController < ApplicationController
  def show

    @document = Document.find_by(id: params[:id])
  #  @document = Document.find_by(docTitle: params[:docTitle])
end
def index
  @documents = Document.all
end

end

app/controllers/image_controller.rb
class ImageController < ApplicationController
  def show
    @image = Image.find_by(id: params[:id])
  end
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  def index
    @lectures = Lecture.all
  end

  def new
     @lecture = Lecture.new
  end

  def create
    @lecture = Lecture.new(lecture_params)
    if @lecture.save
       redirect_to lectures_path, notice: "The lecture #{@lecture.name} has been uploaded."
       @id = @lecture.id
       @attachment = @lecture.attachment
       pdf   = Grim.reap("public"+@attachment.url)
       @count = pdf.count
       for i in 0...@count
       png = pdf[i].save("app/assets/images/#{@id}.#{i}.jpg")
       object = Image.new(:pic => "#{@id}.#{i}.jpg", :lecture_id => "#{@id}" ,
         :no_Of_Pic => "#{i}")
        object.save
      end
    else
      render "new"
    end
  end

  def destroy
   @lecture = Lecture.find(params[:id])
   @lecture.destroy
   redirect_to lectures_path, notice:  "The lecture #{@lecture.name} has been deleted."
  end

  def show
    @lec = Lecture.find_by(id: params[:id])

  end

  private
  def lecture_params
    params.require(:lecture).permit(:name, :attachment)
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController

  def home
  end

  def library
  end

  def upload
  end
end

app/controllers/slide_controller.rb
class SlideController < ApplicationController
  def show
#@slide = Slide.find(params[:slideNumber])
@slide = Slide.find_by(slideNumber: params[:slideNumber])
  end

  def list
    @slides = Slide.all
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/document_helper.rb
module DocumentHelper
end

app/helpers/image_helper.rb
module ImageHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/slide_helper.rb
module SlideHelper
end

app/views/comment/comment.html.erb
<li id="comment-<%= comment.id %>">
<div class="comment">
  <div class="thumbnail">
    <%= image_tag(comment.owner.try(:image_url), class: 'avatar', alt: '') %>
  </div>
  <div class="comment-block">
    <div class="comment-arrow"></div>
    <span class="comment-by">
      <% if commentator_current_user == comment.owner %><%= link_to "×", [commentator, comment], :method => :delete, :remote => true, :confirm => "Are you sure you want to remove this comment?", :disable_with => "×", :class => 'close' %><% end %>
      <strong><%= comment.owner.try(:name) %></strong>
      <% unless local_assigns[:nested_replies] === false %>
        <span class="pull-right reply-button">
          <i class="icon-reply"></i> 
          <%= link_to "Reply", [commentator, :reply, comment], remote: true, class: 'comment-reply' %>
          &nbsp;
        </span>
      <% end %>
    </span>
    <p><%= markdown(comment.body) %></p>
    <span class="date pull-right"><%= time_ago_in_words(comment.created_at) %> ago</span>
  </div>
</div>
<% unless local_assigns[:nested_replies] === false %>
<ul class="comments reply replies">
  <%- comment.replies.each do |reply| %><%= render reply %><%- end %>
</ul>
<% end %>
<div class="reply-form"></div>
</li>

app/views/comment/form.html.erb
<%
comment = local_assigns[:comment]
reply = comment && comment.slideNumber
%>
<div class="post-block post-leave-comment">
  <% unless local_assigns[:prompt] === false %><h5><%= local_assigns[:prompt] || "Leave a Comment" %></h3><% end %>
<%= form_for([commentator, comment || Commentator::Comment.new(commentable: commentable)], remote: true, html: { class: 'comment-form', data: { append: reply ? "#comment-#{comment.slideNumber} > .replies" : "#comments-#{slugify(commentable.to_s)}" } }) do |f| %>
  <%= f.text_area :body, { rows: 5, style: "width:99%" } %>
  <%= f.hidden_field :slideNumber %>
  <%= f.hidden_field :commentable_type %>
  <%= f.hidden_field  :commentable_id %>
  <div class="btn-toolbar">
    <%= f.submit local_assigns[:button_text] || ("Post #{reply ? 'Reply' : 'Comment'}"), class: 'btn btn-primary btn-large' %>
  </div>
<% end %>
</div>

app/views/document/create.html.erb
<h1>Document#create</h1>
<p>Find me in app/views/document/create.html.erb</p>

app/views/document/index.html.erb
<% @documents.each do |doc| %>
<div><%= link_to doc.docTitle ,document_path(doc) %></div> 
<% end %>

app/views/document/show.html.erb
<h3><%= @document.docTitle %></h3>
<% @document.slides.each do |slide| %>
	<%= link_to image_tag(slide.slideURL,height: '32', width: '32' ), "/slide/#{slide.slideNumber}" %>
<% end %>

app/views/image/show.html.erb
<h1>Slide show</h1>
<%= image_tag(@image.pic) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Slides</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/navbar' %><br>
<p class="notice"><%= notice %></p><br>
<p class="alert"><%= alert %></p>
<div class="container" style="padding-top:20px;">
<%= yield %>

</body>
</html>

app/views/lectures/create.html.erb
<h1>Lectures#create</h1>
<p>Find me in app/views/lectures/create.html.erb</p>

app/views/lectures/destroy.html.erb
<h1>Lectures#destroy</h1>
<p>Find me in app/views/lectures/destroy.html.erb</p>

app/views/lectures/index.html.erb
<% if !flash[:notice].blank? %>
  <div class="alert alert-info">
  <%= flash[:notice] %>
  </div>
<% end %>
<br />
<%= link_to "New Lecture", new_lecture_path, class: "btn btn-primary" %>
<br />
<br />
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Download Link</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @lectures.each do |lecture| %>
      <tr>
        <td><%= link_to lecture.name,lecture_path(lecture) %></td>
        <td><%= link_to "Download Lecture", lecture.attachment_url %></td>
        <td><%= button_to "Delete",  lecture, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{lecture.name}?" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/lectures/new.html.erb
<% if !@lecture.errors.empty? %>
  <div class="alert alert-error">
    <ul>
      <% @lecture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="well">
  <%= form_for @lecture, html: { multipart: true } do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :attachment %>
    <%= f.file_field :attachment %>
    <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/lectures/show.html.erb
<h3><%= @lec.name %></h3>
<% @lec.image.each do |image| %>
	<%= link_to image_tag(image.pic,height: '200', width: '200' ), "/image/#{image.id}" %>
<% end %>

app/views/page/home.html.erb
<h1>Page#home</h1>
<p>Find me in app/views/page/home.html.erb</p>

app/views/page/library.html.erb
<%= render 'document/list' %>

app/views/page/upload.html.erb
<h1>Page#upload</h1>
<p>Find me in app/views/page/upload.html.erb</p>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
    <li class="active"><%= link_to "Home", root_path %></li>
    <li><%= link_to "Documents",index_path %></li>
    <li><%= link_to "Upload", new_path %></li>
    <% if user_signed_in? %>
    <li>  <%= link_to "Sign out",destroy_user_session_path, method: :delete %></li>
    <% else %>
     <li><%= link_to "Sign in",new_user_session_path %></li>
    <li> <%= link_to "Sign up",new_user_registration_path %></li>
    <% end %>
 </ul>
</div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>

app/views/slide/show.html.erb
<h1>Slide show</h1>
<%= image_tag(@slide.slideURL) %> <br>